"""news items

Revision ID: 6b61cbd2287d
Revises: 9114f9b5c224
Create Date: 2026-09-02 01:21:51.315405

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b61cbd2287d'
down_revision: str | None = '9114f9b5c224'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_guid'), 'news_items', ['guid'], unique=True)
    op.create_index('ix_news_published', 'news_items', ['published_at'], unique=False)
    op.create_index('ix_news_source', 'news_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_source', table_name='news_items')
    op.drop_index('ix_news_published', table_name='news_items')
    op.drop_index(op.f('ix_news_items_guid'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
