"""market analytics schema

Revision ID: 9114f9b5c224
Revises: 0001
Create Date: 2026-08-24 19:34:31.543081

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9114f9b5c224'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compute_runs_kind'), 'compute_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_compute_runs_started_at'), 'compute_runs', ['started_at'], unique=False)
    op.create_table('correlation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('matrix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of', 'window', name='uq_correlation_key')
    )
    op.create_index(op.f('ix_correlation_snapshots_as_of'), 'correlation_snapshots', ['as_of'], unique=False)
    op.create_table('macro_series',
    sa.Column('series_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('units', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index(op.f('ix_macro_series_category'), 'macro_series', ['category'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_features', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('baseline_accuracy', sa.Float(), nullable=True),
    sa.Column('edge_vs_baseline', sa.Float(), nullable=True),
    sa.Column('top_decile_precision', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_is_active'), 'model_runs', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_runs_target'), 'model_runs', ['target'], unique=False)
    op.create_index(op.f('ix_model_runs_trained_at'), 'model_runs', ['trained_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of', 'target', 'model', name='uq_predictions_key')
    )
    op.create_index('ix_predictions_asof_target', 'predictions', ['as_of', 'target'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of', 'kind', name='uq_signals_key')
    )
    op.create_index('ix_signals_asof', 'signals', ['as_of'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('ret_1d', sa.Float(), nullable=True),
    sa.Column('ret_5d', sa.Float(), nullable=True),
    sa.Column('ret_21d', sa.Float(), nullable=True),
    sa.Column('ret_63d', sa.Float(), nullable=True),
    sa.Column('ret_252d', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('vol_20d', sa.Float(), nullable=True),
    sa.Column('vol_ratio_10_60', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('pct_from_52w_high', sa.Float(), nullable=True),
    sa.Column('drawdown_pct', sa.Float(), nullable=True),
    sa.Column('volume_z', sa.Float(), nullable=True),
    sa.Column('rel_strength_21d', sa.Float(), nullable=True),
    sa.Column('px_over_sma200', sa.Float(), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of', name='uq_snapshots_symbol_date')
    )
    op.create_index('ix_snapshots_as_of', 'snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_snapshots_symbol'), 'snapshots', ['symbol'], unique=False)
    op.create_table('macro_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=40), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'obs_date', name='uq_macro_obs')
    )
    op.create_index('ix_macro_obs_series_date', 'macro_observations', ['series_id', 'obs_date'], unique=False)
    op.drop_index('ix_transactions_executed_at', table_name='transactions')
    op.drop_index('ix_transactions_portfolio_id', table_name='transactions')
    op.drop_index('ix_transactions_symbol', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('portfolios')
    op.drop_index('ix_revenue_streams_start_date', table_name='revenue_streams')
    op.drop_table('revenue_streams')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_index('ix_expenses_start_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('watchlist_items')
    op.drop_table('cash_snapshots')
    # instruments is reference data that the worker repopulates from
    # app/universe.py on every run, so emptying it is safe and avoids the
    # classic autogenerate failure: adding a NOT NULL column with no
    # server_default to a table that already has rows.
    op.execute("DELETE FROM instruments")

    # ADD COLUMN does NOT create the enum type -- only CREATE TABLE does. A
    # sa.Enum() referenced from add_column therefore fails with
    #   type "asset_group" does not exist
    # unless the type is created explicitly first. Autogenerate never emits it.
    asset_group_enum = postgresql.ENUM(
        'index', 'sector', 'bond', 'commodity', 'crypto', 'volatility', 'equity',
        name='asset_group',
    )
    asset_group_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('instruments', sa.Column('asset_group', asset_group_enum, nullable=False))
    op.add_column('instruments', sa.Column('sector', sa.String(length=80), nullable=False))
    op.add_column('instruments', sa.Column('short_label', sa.String(length=40), nullable=False))
    op.add_column('instruments', sa.Column('universe', sa.String(length=24), nullable=False))
    op.add_column('instruments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('instruments', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_instruments_asset_group'), 'instruments', ['asset_group'], unique=False)
    op.create_index(op.f('ix_instruments_is_active'), 'instruments', ['is_active'], unique=False)
    op.create_index(op.f('ix_instruments_sector'), 'instruments', ['sector'], unique=False)
    op.create_index(op.f('ix_instruments_universe'), 'instruments', ['universe'], unique=False)
    op.drop_column('instruments', 'currency')
    op.drop_column('instruments', 'asset_class')
    op.create_index('ix_price_bars_date', 'price_bars', ['bar_date'], unique=False)
    # Postgres ENUM types outlive the tables that used them. Autogenerate does
    # not emit these drops, so without this they linger forever and a
    # downgrade/upgrade cycle fails with "type already exists".
    for enum_name in ("txn_type", "revenue_interval", "expense_interval", "asset_class"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_bars_date', table_name='price_bars')
    # Same trap as the upgrade, mirrored: upgrade() dropped this type, and
    # ADD COLUMN will not recreate it. Without this the downgrade fails with
    #   type "asset_class" does not exist
    asset_class_enum = postgresql.ENUM(
        'equity', 'etf', 'crypto', 'cash', 'other', name='asset_class'
    )
    asset_class_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('instruments', sa.Column('asset_class', asset_class_enum, server_default=sa.text("'equity'::asset_class"), autoincrement=False, nullable=False))
    op.add_column('instruments', sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_instruments_universe'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_sector'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_is_active'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_group'), table_name='instruments')
    op.drop_column('instruments', 'added_at')
    op.drop_column('instruments', 'is_active')
    op.drop_column('instruments', 'universe')
    op.drop_column('instruments', 'short_label')
    op.drop_column('instruments', 'sector')
    op.drop_column('instruments', 'asset_group')
    op.create_table('cash_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cash_snapshots_pkey'),
    sa.UniqueConstraint('as_of', name='cash_snapshots_as_of_key')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='watchlist_items_pkey'),
    sa.UniqueConstraint('symbol', name='watchlist_items_symbol_key')
    )
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=160), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('interval', postgresql.ENUM('monthly', 'annual', 'one_time', name='expense_interval'), server_default=sa.text("'monthly'::expense_interval"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='expenses_pkey')
    )
    op.create_index('ix_expenses_start_date', 'expenses', ['start_date'], unique=False)
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_table('revenue_streams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('customer', sa.VARCHAR(length=160), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('interval', postgresql.ENUM('monthly', 'annual', 'one_time', name='revenue_interval'), server_default=sa.text("'monthly'::revenue_interval"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revenue_streams_pkey')
    )
    op.create_index('ix_revenue_streams_start_date', 'revenue_streams', ['start_date'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('portfolios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='portfolios_pkey'),
    sa.UniqueConstraint('name', name='portfolios_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('buy', 'sell', 'dividend', name='txn_type'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=18, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('executed_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='transactions_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_index('ix_transactions_symbol', 'transactions', ['symbol'], unique=False)
    op.create_index('ix_transactions_portfolio_id', 'transactions', ['portfolio_id'], unique=False)
    op.create_index('ix_transactions_executed_at', 'transactions', ['executed_at'], unique=False)
    op.drop_index('ix_macro_obs_series_date', table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_index(op.f('ix_snapshots_symbol'), table_name='snapshots')
    op.drop_index('ix_snapshots_as_of', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_asof', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index('ix_predictions_asof_target', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_runs_trained_at'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_target'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_is_active'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_macro_series_category'), table_name='macro_series')
    op.drop_table('macro_series')
    op.drop_index(op.f('ix_correlation_snapshots_as_of'), table_name='correlation_snapshots')
    op.drop_table('correlation_snapshots')
    op.drop_index(op.f('ix_compute_runs_started_at'), table_name='compute_runs')
    op.drop_index(op.f('ix_compute_runs_kind'), table_name='compute_runs')
    op.drop_table('compute_runs')
    # Drop what upgrade() created, so upgrade->downgrade->upgrade works.
    op.execute("DROP TYPE IF EXISTS asset_group")
    op.execute("DROP TYPE IF EXISTS run_status")

    # ### end Alembic commands ###
