"""earnings dates

Revision ID: eeb33d772541
Revises: 6b61cbd2287d
Create Date: 2026-09-06 00:01:34.820618

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eeb33d772541'
down_revision: str | None = '6b61cbd2287d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'earnings_date', name='uq_earnings_symbol_date')
    )
    op.create_index('ix_earnings_symbol_date', 'earnings_dates', ['symbol', 'earnings_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_earnings_symbol_date', table_name='earnings_dates')
    op.drop_table('earnings_dates')
    # ### end Alembic commands ###
